version: '3.5'
services:

  discovery:
    container_name: "discovery"
    image: consul:1.7
    ports:
      - 8500:8500

  gateway:
    container_name: "gateway"
    image: projet8/gateway
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery

  authws:
    container_name: "authws"
    restart: "on-failure"
    image: projet8/authws
    #restart: always
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DKEYCLOAK_HOST=keycloak -DKEYCLOAK_PORT=8080
    ports:
      - 8081:8081
    depends_on:
      - discovery
      - keycloak

  communityws:
    container_name: "communityws"
    restart: "on-failure"
    image: projet8/communityws
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DKEYCLOAK_HOST=keycloak -DKEYCLOAK_PORT=8080 -DMONGO_HOST=mongo-community -DMONGO_PORT=27118
    depends_on:
      - discovery
      - mongo-community
    ports:
    - 8082:8082

  coursews:
    container_name: "coursews"
    restart: "on-failure"
    image: projet8/coursews
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DKEYCLOAK_HOST=keycloak -DKEYCLOAK_PORT=8080 -DMONGO_HOST=mongo-course -DMONGO_PORT=27117
    depends_on:
      - discovery
      - mongo-course
    ports:
    - 8083:8083

  mongo-course:
    container_name: "mongo-course"
    build: mongocourse/
    command: mongod --port 27117
    ports:
      - 27117:27117

  mongo-community:
    container_name: "mongo-community"
    build: mongocommunity/
    command: mongod --port 27118
    ports:
      - 27118:27118

  dc-postgres:
    container_name: "dc-postgres"
    image: postgres
    environment:
      POSTGRES_DB: "db_auth"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5430:5430"
    expose:
      - "5430"
    restart: always
    command: -p 5430

  keycloak:
    container_name: "keycloak"
    image: jboss/keycloak:11.0.2
    command: "-b 0.0.0.0"
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=dc-postgres:5430
      - DB_DATABASE=db_auth
      - DB_USER=postgres
      - DB_SCHEMA=public
      - DB_PASSWORD=postgres
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
    volumes:
      - ./realm.json:/tmp/realm.json
    ports:
      - 8300:8080
    expose:
      - 8300
    depends_on:
      - dc-postgres
